# Generated by Django 5.1.7 on 2025-03-19 15:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=500)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RouteInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('halt_type', models.CharField(choices=[('STOP', 'Stop'), ('BREAK', 'Break')], max_length=10)),
                ('duration', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'route_instruction',
                'constraints': [models.CheckConstraint(condition=models.Q(('duration__gte', 0)), name='duration_gte_0')],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_used', models.IntegerField()),
                ('distance', models.FloatField(default=0)),
                ('dropoff_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dropoff_trips', to='api.location')),
                ('pickup_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_trips', to='api.location')),
                ('route_instructions', models.ManyToManyField(related_name='trips', to='api.routeinstruction')),
            ],
            options={
                'db_table': 'trip',
            },
        ),
        migrations.CreateModel(
            name='LogSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_trip', models.DateField(default=django.utils.timezone.now)),
                ('duty_status', models.CharField(choices=[('OFF_DUTY', 'Off Duty'), ('SLEEPER_BERTH', 'Sleeper Berth'), ('DRIVING', 'Driving'), ('ON_DUTY', 'On Duty (Not Driving)')], max_length=20)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_sheets', to='api.trip')),
            ],
            options={
                'db_table': 'log_sheet',
            },
        ),
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.CheckConstraint(condition=models.Q(('cycle_used__gte', 0)), name='cycle_used_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.CheckConstraint(condition=models.Q(('distance__gte', 0)), name='distance_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='logsheet',
            constraint=models.CheckConstraint(condition=models.Q(('start_time__lte', models.F('end_time'))), name='start_time_lte_end_time'),
        ),
    ]
