# Generated by Django 5.1.7 on 2025-03-19 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_trip_current_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='distance',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='route_instructions',
            field=models.ManyToManyField(blank=True, related_name='trips', to='api.routeinstruction'),
        ),
    ]
