# Generated by Django 5.1.7 on 2025-03-21 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_trip_distance_alter_trip_route_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='routeinstruction',
            name='current_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_route_instructions', to='api.location'),
        ),
        migrations.AddField(
            model_name='routeinstruction',
            name='day',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='trip',
            name='number_of_days',
            field=models.IntegerField(default=1),
        ),
    ]
